import { z } from "zod";

const option = (id: string, label: string) => ({ id, label });

export const waitingGameSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  type: z.enum(["multiple_choice", "quiz", "slider", "tap_action", "prediction"]),
  category: z.string().min(1),
  question: z.string().min(1),
  options: z.array(z.object({ id: z.string(), label: z.string() })).min(2).max(8),
  correctOptionId: z.string().optional(),
  shareLevel: z.enum(["private", "soft_share", "direct_share"]),
});

export type WaitingGame = z.infer<typeof waitingGameSchema>;

export const waitingGames: WaitingGame[] = [
  { id:"bird",title:"De fluitvogel-test",type:"tap_action",category:"ludiek",question:"Welk vogeltje past bij je humeur?",options:[option("merel","Merel"),option("duif","Duif"),option("pauw","Pauw"),option("kraai","Kraai")],shareLevel:"soft_share" },
  { id:"campfire",title:"Kampvuurhouding",type:"multiple_choice",category:"ludiek",question:"Bij een kampvuur ben jij eerder...",options:[option("story","Verhalenverteller"),option("quiet","Stille kijker"),option("snack","Snackbewaker"),option("smoke","Rook in mijn gezicht")],shareLevel:"soft_share" },
  { id:"kilo",title:"1 kilo veren of stenen?",type:"quiz",category:"kennis",question:"Wat is zwaarder?",options:[option("feathers","Veren"),option("stones","Stenen"),option("equal","Even zwaar")],correctOptionId:"equal",shareLevel:"private" },
  { id:"flower",title:"Mooiste bloem",type:"tap_action",category:"verbindend",question:"Welke bloem geef je aan je partner?",options:[option("daisy","Madelief"),option("rose","Roos"),option("tulip","Tulp"),option("lavender","Lavendel")],shareLevel:"direct_share" },
  { id:"day",title:"Moment van de dag",type:"multiple_choice",category:"persoonlijk",question:"Als jij een moment van de dag was...",options:[option("morning","Ochtend"),option("afternoon","Middag"),option("dusk","Schemering"),option("night","Nacht")],shareLevel:"soft_share" },
  { id:"frogs",title:"Kikkers bij de vijver",type:"quiz",category:"kennis",question:"3 kikkers zitten er. 2 komen erbij en 1 springt weg. Hoeveel blijven?",options:[option("3","3"),option("4","4"),option("5","5")],correctOptionId:"4",shareLevel:"private" },
  { id:"waiting-place",title:"Waar wacht jij het liefst?",type:"multiple_choice",category:"sfeer",question:"Kies je favoriete wachtplek.",options:[option("fire","Kampvuur"),option("bridge","Brug"),option("pond","Vijver"),option("bench","Bankje"),option("gate","Dorpspoort")],shareLevel:"soft_share" },
  { id:"compliment",title:"Complimentenpot",type:"multiple_choice",category:"verbindend",question:"Kies alvast een mini-compliment.",options:[option("curious","Nieuwsgierig"),option("calm","Rustig"),option("funny","Grappig"),option("brave","Moedig"),option("kind","Vriendelijk")],shareLevel:"direct_share" },
  { id:"partner-guess",title:"Raad je partner",type:"prediction",category:"ludiek",question:"Wat doet je partner waarschijnlijk?",options:[option("phone","Telefoon zoeken"),option("read","Alles lezen"),option("laugh","Lachen"),option("click","Rustig klikken")],shareLevel:"soft_share" },
  { id:"stone",title:"Steentje gooien",type:"tap_action",category:"ludiek",question:"Hoeveel sprongen maakt jouw steentje?",options:[option("soft","Rustige worp"),option("fast","Snelle worp"),option("wild","Wilde worp")],shareLevel:"private" },
  { id:"compass",title:"Karakterkompas",type:"multiple_choice",category:"persoonlijk",question:"Vandaag ben ik vooral...",options:[option("head","Hoofd"),option("heart","Hart"),option("hands","Handen"),option("chaos","Chaos")],shareLevel:"soft_share" },
  { id:"animal",title:"Dier van het Beginland",type:"multiple_choice",category:"ludiek",question:"Welk dier ben jij nu?",options:[option("fox","Vos"),option("bear","Beer"),option("squirrel","Eekhoorn"),option("deer","Hert"),option("dog","Hond")],shareLevel:"soft_share" },
  { id:"word",title:"Een-woord-warming-up",type:"multiple_choice",category:"persoonlijk",question:"Het woord is 'thuis'. Dat voelt...",options:[option("warm","Warm"),option("exciting","Spannend"),option("funny","Grappig"),option("hard","Moeilijk")],shareLevel:"soft_share" },
  { id:"memory",title:"Mini-memory",type:"tap_action",category:"ludiek",question:"Kies intuïtief twee kaartjes.",options:[option("moon","Maan + ster"),option("fire","Vuur + thee"),option("leaf","Blad + bloem"),option("path","Pad + brug")],shareLevel:"private" },
  { id:"bridge",title:"De brugvraag",type:"multiple_choice",category:"persoonlijk",question:"Wat hoop je aan de overkant te vinden?",options:[option("peace","Rust"),option("fun","Lol"),option("honesty","Eerlijkheid"),option("surprise","Verrassing"),option("courage","Moed")],shareLevel:"soft_share" },
  { id:"snack",title:"Kampvuur-snack",type:"multiple_choice",category:"ludiek",question:"Wat neem je mee naar het vuur?",options:[option("mallow","Marshmallow"),option("bread","Broodje"),option("apple","Appel"),option("tea","Thee"),option("nothing","Niets")],shareLevel:"soft_share" },
  { id:"route",title:"Snelste route",type:"tap_action",category:"ludiek",question:"Via welk pad loop je naar het kampvuur?",options:[option("flowers","Langs de bloemen"),option("water","Langs het water"),option("bridge","Over de brug")],shareLevel:"private" },
  { id:"mood",title:"Stemmingbarometer",type:"slider",category:"persoonlijk",question:"Waar zit je nu?",options:[option("1","Ik moet nog landen"),option("2","Rustig"),option("3","Neutraal"),option("4","Nieuwsgierig"),option("5","Kom maar op")],shareLevel:"soft_share" },
  { id:"frog-bench",title:"Kikker op je bankje",type:"multiple_choice",category:"humor",question:"Er zit een kikker op je bankje. Jij...",options:[option("sit","Gaat ernaast zitten"),option("talk","Praat ermee"),option("henk","Noemt hem Henk"),option("leave","Zoekt een ander bankje")],shareLevel:"soft_share" },
  { id:"prediction",title:"Geheime voorspelling",type:"prediction",category:"verbindend",question:"Ik voorspel dat wij straks...",options:[option("laugh","Lachen"),option("wander","Afdwalen"),option("serious","Serieus worden"),option("discover","Iets ontdekken"),option("surprise","Verrast zijn")],shareLevel:"direct_share" },
  { id:"season",title:"Welk seizoen ben jij?",type:"multiple_choice",category:"persoonlijk",question:"Welk seizoen past vandaag bij je?",options:[option("spring","Lente"),option("summer","Zomer"),option("autumn","Herfst"),option("winter","Winter")],shareLevel:"soft_share" },
  { id:"octopus",title:"Waar of niet waar?",type:"quiz",category:"kennis",question:"Een octopus heeft drie harten.",options:[option("true","Waar"),option("false","Niet waar")],correctOptionId:"true",shareLevel:"private" },
  { id:"power",title:"Kies je superkracht",type:"multiple_choice",category:"ludiek",question:"Welke superkracht wil je nu?",options:[option("mind","Gedachten lezen"),option("fly","Vliegen"),option("pause","Tijd pauzeren"),option("animals","Dieren verstaan"),option("cook","Perfect koken")],shareLevel:"soft_share" },
  { id:"music",title:"Muziekstemming",type:"multiple_choice",category:"persoonlijk",question:"Welke muziek past nu bij je?",options:[option("calm","Rustig"),option("happy","Vrolijk"),option("drama","Dramatisch"),option("dance","Dansbaar"),option("silent","Stil")],shareLevel:"soft_share" },
  { id:"traits",title:"Drie dingen over jou",type:"multiple_choice",category:"persoonlijk",question:"Welke eigenschap staat nu vooraan?",options:[option("curious","Nieuwsgierig"),option("loyal","Loyaal"),option("chaotic","Chaotisch"),option("calm","Rustig"),option("funny","Grappig"),option("sensitive","Gevoelig")],shareLevel:"soft_share" },
  { id:"math",title:"Snelle rekensom",type:"quiz",category:"kennis",question:"Wat is 6 x 2?",options:[option("10","10"),option("12","12"),option("14","14")],correctOptionId:"12",shareLevel:"private" },
  { id:"color",title:"Welke kleur ben jij?",type:"multiple_choice",category:"persoonlijk",question:"Welke kleur ben je nu?",options:[option("yellow","Geel"),option("blue","Blauw"),option("green","Groen"),option("red","Rood"),option("purple","Paars")],shareLevel:"soft_share" },
  { id:"thanks",title:"Dankbaarheidsmoment",type:"multiple_choice",category:"verbindend",question:"Waar ben je vandaag dankbaar voor?",options:[option("peace","Rust"),option("people","Mensen"),option("food","Eten"),option("work","Werk"),option("humor","Humor"),option("nature","Natuur")],shareLevel:"soft_share" },
  { id:"path",title:"Kies een pad",type:"tap_action",category:"sfeer",question:"Welk pad roept je?",options:[option("bridge","Naar de brug"),option("village","Naar het dorp"),option("pond","Naar de vijver"),option("forest","Naar het bos"),option("fire","Naar het vuur")],shareLevel:"soft_share" },
  { id:"taste",title:"Welke smaak?",type:"multiple_choice",category:"ludiek",question:"Welke smaak past bij jou nu?",options:[option("sweet","Zoet"),option("salt","Zout"),option("sour","Zuur"),option("bitter","Bitter"),option("umami","Umami"),option("spicy","Pittig")],shareLevel:"soft_share" },
  { id:"towel",title:"Raadseltje",type:"quiz",category:"kennis",question:"Wat wordt natter hoe meer het droogt?",options:[option("sun","De zon"),option("towel","Een handdoek"),option("soap","Zeep")],correctOptionId:"towel",shareLevel:"private" },
  { id:"film",title:"Welke film past?",type:"multiple_choice",category:"ludiek",question:"Jouw dag als filmgenre...",options:[option("comedy","Komedie"),option("adventure","Avontuur"),option("drama","Drama"),option("docu","Documentaire"),option("fantasy","Fantasy"),option("romcom","Romcom")],shareLevel:"soft_share" },
  { id:"energy",title:"Energieniveau",type:"slider",category:"persoonlijk",question:"Waar zit je energie?",options:[option("1","Slaapstand"),option("2","Traag"),option("3","Prima"),option("4","Energiek"),option("5","Springveer")],shareLevel:"soft_share" },
  { id:"place",title:"Kies een plek",type:"multiple_choice",category:"sfeer",question:"Waar zou je nu willen zitten?",options:[option("tree","Onder een boom"),option("water","Bij water"),option("market","Op het plein"),option("fire","Bij het vuur"),option("bridge","Op de brug")],shareLevel:"soft_share" },
  { id:"gnome",title:"Wat zou je doen?",type:"multiple_choice",category:"humor",question:"Een kabouter vraagt de weg. Jij...",options:[option("help","Helpt serieus"),option("cookies","Vraagt koekjes"),option("walk","Loopt mee"),option("dream","Denkt dat je droomt")],shareLevel:"soft_share" },
  { id:"proverb",title:"Spreekwoordquiz",type:"quiz",category:"kennis",question:"De appel valt niet ver van...",options:[option("tree","de boom"),option("basket","de mand"),option("garden","de tuin")],correctOptionId:"tree",shareLevel:"private" },
  { id:"emotion",title:"Emotie-icoon",type:"tap_action",category:"persoonlijk",question:"Welke emotie past nu?",options:[option("laugh","Lachend"),option("tired","Moe"),option("curious","Nieuwsgierig"),option("tense","Gespannen"),option("calm","Kalm"),option("cheeky","Ondeugend")],shareLevel:"soft_share" },
  { id:"learned",title:"Vandaag geleerd",type:"multiple_choice",category:"reflectief",question:"Wat heb je vandaag vooral geleerd?",options:[option("patience","Geduld"),option("release","Loslaten"),option("persist","Doorzetten"),option("laugh","Lachen"),option("practical","Iets praktisch")],shareLevel:"soft_share" },
  { id:"companion",title:"Kies je metgezel",type:"multiple_choice",category:"ludiek",question:"Wie neem je mee op reis?",options:[option("owl","Wijze uil"),option("dog","Trouwe hond"),option("fox","Snelle vos"),option("bear","Sterke beer"),option("duck","Vrolijke eend")],shareLevel:"soft_share" },
  { id:"message",title:"Eindboodschap",type:"multiple_choice",category:"verbindend",question:"Kies een boodschap voor je partner.",options:[option("welcome","Leuk dat je er bent"),option("curious","Ik ben benieuwd"),option("laugh","Laten we lachen"),option("calm","Rustig aan"),option("ready","Kom maar op")],shareLevel:"direct_share" },
].map((game) => waitingGameSchema.parse(game));
